Please add your personal information at the first cell by "Markdown" selection.
# 2024-Spring DS HW2
## Due: 2024/03/26 23:59
## 檔名請更為HW2_${學號}.ipynb 例如:HW2_111598084.ipynb
### Problem1: 
參考Lab3，請用pandas分析2024/03/11股市的開盤價和收盤價的平均值和標準差。

### Problem2:
參考Lab4:
- 請問2024/3/18日台灣股市收盤價每一股超過1000元的股票有幾家公司? 
- 這幾家每股超過1000元的平均收盤價是多少? 
- 目前股王是哪一家公司? 

In [74]:
# HW2 Problem1

import pandas as pd
import numpy as np
import requests

# get stock information

date = "20240311"
url = f'https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&date={date}&type=ALLBUT0999'
response = requests.get(url)
stock_json = response.json()
stock_data = pd.DataFrame(stock_json['data9'],columns=stock_json['fields9'])
origin_data = stock_data.copy()

# Get 開盤價以及收盤價 information

open_price = np.array(stock_data['開盤價'])
close_price = np.array(stock_data['收盤價'])

# 過濾當天未有交易資訊的股票，下市那種

open_haveprice = open_price!='--'
close_haveprice = close_price!='--'



print("找開盤價有逗號的")

# finding 開盤價那些有逗號的
print(np.where(open_price == '1,055.00'))
open_price[327] = '1055'
print(np.where(open_price == '1,300.00'))
open_price[419] = '1300'
print(np.where(open_price == '1,235.00'))
open_price[555] = '1235'
print(np.where(open_price == '2,515.00'))
open_price[722] = '2515'
print(np.where(open_price == '1,510.00'))
open_price[803] = '1510'
print(np.where(open_price == '1,145.00'))
open_price[816] = '1145'
print(np.where(open_price == '3,830.00'))
open_price[837] = '3830'
print(np.where(open_price == '2,180.00'))
open_price[939] = '2180'
print(np.where(open_price == '1,625.00'))
open_price[1027] = '1625'
print(np.where(open_price == '2,490.00'))
open_price[1077] = '2490'

open_price = open_price[open_haveprice].astype(float)

print()
print("找收盤價有逗號的")

# finding 收盤價那些有逗號的

print(np.where(close_price == '1,065.00'))
close_price[327] = '1065'
print(np.where(close_price == '1,310.00'))
close_price[419] = '1310'
print(np.where(close_price == '1,225.00'))
close_price[555] = '1225'
print(np.where(close_price == '2,520.00'))
close_price[722] = '2520'
print(np.where(close_price == '1,475.00'))
close_price[803] = '1475'
print(np.where(close_price == '1,190.00'))
close_price[816] = '1190'
print(np.where(close_price == '3,750.00'))
close_price[837] = '3750'
print(np.where(close_price == '2,290.00'))
close_price[939] = '2290'
print(np.where(close_price == '1,660.00'))
close_price[1027] = '1660'
print(np.where(close_price == '2,430.00'))
close_price[1077] = '2430'

close_price = close_price[close_haveprice].astype(float)

print(open_price)
print(close_price)

print()
print("以下是2024/03/11當日台北股市資訊")


print("開盤價平均", open_price.mean())
print("開盤價標準差", open_price.std())
print("收盤價平均", close_price.mean())
print("收盤價標準差",close_price.std() )

找開盤價有逗號的
(array([327], dtype=int64),)
(array([419], dtype=int64),)
(array([555], dtype=int64),)
(array([722], dtype=int64),)
(array([803], dtype=int64),)
(array([816], dtype=int64),)
(array([837], dtype=int64),)
(array([939], dtype=int64),)
(array([1027], dtype=int64),)
(array([1077], dtype=int64),)

找收盤價有逗號的
(array([327], dtype=int64),)
(array([419], dtype=int64),)
(array([555], dtype=int64),)
(array([722], dtype=int64),)
(array([803], dtype=int64),)
(array([816], dtype=int64),)
(array([837], dtype=int64),)
(array([939], dtype=int64),)
(array([1027], dtype=int64),)
(array([1077], dtype=int64),)
[153.85  76.65 155.95 ...  24.9   25.55 233.  ]
[152.9   77.2  155.25 ...  24.45  25.15 230.5 ]

以下是2024/03/11當日台北股市資訊
開盤價平均 83.86246721311474
開盤價標準差 205.57313292687806
收盤價平均 84.33819672131148
收盤價標準差 205.624676296786


In [109]:
# HW2 Problem2

import pandas as pd
import numpy as np
import requests

# Get stock information

date = "20240318"
url = f'https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&date={date}&type=ALLBUT0999'
response = requests.get(url)
stock_json = response.json()
stock_data = pd.DataFrame(stock_json['data9'],columns=stock_json['fields9'])
origin_data = stock_data.copy()

# 過濾那些價格有逗號或是當天無開盤資訊導致--的資訊

replace = {',':'','--':np.nan}

stock_data = stock_data.replace(replace,regex=True)
stock_data = stock_data.apply(pd.to_numeric,errors='ignore')

# 過濾當天收盤價不到1000元的雞蛋水餃股

stock_data = stock_data[stock_data.收盤價>=1000]

# 將收盤價轉成numpy array

average = np.array(stock_data['收盤價'])

# 取得當天共有幾家破千元的股票以及平均股價

print("在當天收盤前總共有",len(stock_data),"家公司股價超過千元")
print("當天這些公司的平均股價是", average.mean())

# 取得股王股價

stock_max_money = stock_data.收盤價.max()
stock_name = stock_data[stock_data.收盤價>=stock_max_money]

stock_name.head()
#print(stock_name.證券名稱[838])
#print( stock_name[0])
print("統計到3/18，台股股王是",stock_name.證券名稱[838],"價格為", stock_max_money)
    

在當天收盤前總共有 10 家公司股價超過千元
當天這些公司的平均股價是 1862.5
統計到3/18，台股股王是 世芯-KY 價格為 3665.0
